export const REGISTER_HOLIDAY_BY_DATE_REQUEST = 'REGISTER_HOLIDAY_BY_DATE_REQUEST'
export const REGISTER_HOLIDAY_BY_DATE_SUCCESS = 'REGISTER_HOLIDAY_BY_DATE_SUCCESS'
export const REGISTER_HOLIDAY_BY_DATE_FAIL = 'REGISTER_HOLIDAY_BY_DATE_FAIL'
export const REGISTER_HOLIDAY_BY_DATE_RESET = 'REGISTER_HOLIDAY_BY_DATE_RESET'

export const DELETE_HOLIDAY_BY_ID_REQUEST = 'DELETE_HOLIDAY_BY_ID_REQUEST'
export const DELETE_HOLIDAY_BY_ID_SUCCESS = 'DELETE_HOLIDAY_BY_ID_SUCCESS'
export const DELETE_HOLIDAY_BY_ID_FAIL = 'DELETE_HOLIDAY_BY_ID_FAIL'
export const DELETE_HOLIDAY_BY_ID_RESET = 'DELETE_HOLIDAY_BY_ID_RESET'
