export const GET_KARATE_CLASS_BY_ADMIN_REQUEST = 'GET_KARATE_CLASS_BY_ADMIN_REQUEST'
export const GET_KARATE_CLASS_BY_ADMIN_SUCCESS = 'GET_KARATE_CLASS_BY_ADMIN_SUCCESS'
export const GET_KARATE_CLASS_BY_ADMIN_FAIL = 'GET_KARATE_CLASS_BY_ADMIN_FAIL'
export const GET_KARATE_CLASS_BY_ADMIN_RESET = 'GET_KARATE_CLASS_BY_ADMIN_RESET'

export const REGISTER_KARATE_CLASS_REQUEST = 'REGISTER_KARATE_CLASS_REQUEST'
export const REGISTER_KARATE_CLASS_SUCCESS = 'REGISTER_KARATE_CLASS_SUCCESS'
export const REGISTER_KARATE_CLASS_FAIL = 'REGISTER_KARATE_CLASS_FAIL'
export const REGISTER_KARATE_CLASS_RESET = 'REGISTER_KARATE_CLASS_RESET'
