export const RESET_ATTENDANCE_SYSTEM_REQUEST = 'RESET_ATTENDANCE_SYSTEM_REQUEST'
export const RESET_ATTENDANCE_SYSTEM_SUCCESS = 'RESET_ATTENDANCE_SYSTEM_SUCCESS'
export const RESET_ATTENDANCE_SYSTEM_FAIL = 'RESET_ATTENDANCE_SYSTEM_FAIL'
export const RESET_ATTENDANCE_SYSTEM_RESET = 'RESET_ATTENDANCE_SYSTEM_RESET' 