export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const GET_STUDENT_USERS_REQUEST = 'GET_STUDENT_USERS_REQUEST'
export const GET_STUDENT_USERS_SUCCESS = 'GET_STUDENT_USERS_SUCCESS'
export const GET_STUDENT_USERS_FAIL = 'GET_STUDENT_USERS_FAIL'
export const GET_STUDENT_USERS_RESET = 'GET_STUDENT_USERS_RESET'

export const REGISTER_STUDENTS_REQUEST = 'REGISTER_STUDENTS_REQUEST'
export const REGISTER_STUDENTS_SUCCESS = 'REGISTER_STUDENTS_SUCCESS'
export const REGISTER_STUDENTS_FAIL = 'REGISTER_STUDENTS_FAIL'
export const REGISTER_STUDENTS_RESET = 'REGISTER_STUDENTS_RESET'

export const GET_STUDENT_USER_BY_ID_REQUEST = 'GET_STUDENT_USER_BY_ID_REQUEST'
export const GET_STUDENT_USER_BY_ID_SUCCESS = 'GET_STUDENT_USER_BY_ID_SUCCESS'
export const GET_STUDENT_USER_BY_ID_FAIL = 'GET_STUDENT_USER_BY_ID_FAIL'
export const GET_STUDENT_USER_BY_ID_RESET = 'GET_STUDENT_USER_BY_ID_RESET'

export const UPDATE_STUDENT_USER_BY_ID_REQUEST = 'UPDATE_STUDENT_USER_BY_ID_REQUEST'
export const UPDATE_STUDENT_USER_BY_ID_SUCCESS = 'UPDATE_STUDENT_USER_BY_ID_SUCCESS'
export const UPDATE_STUDENT_USER_BY_ID_FAIL = 'UPDATE_STUDENT_USER_BY_ID_FAIL'
export const UPDATE_STUDENT_USER_BY_ID_RESET = 'UPDATE_STUDENT_USER_BY_ID_RESET'

export const DELETE_STUDENT_USER_BY_ID_REQUEST = 'DELETE_STUDENT_USER_BY_ID_REQUEST'
export const DELETE_STUDENT_USER_BY_ID_SUCCESS = 'DELETE_STUDENT_USER_BY_ID_SUCCESS'
export const DELETE_STUDENT_USER_BY_ID_FAIL = 'DELETE_STUDENT_USER_BY_ID_FAIL'
export const DELETE_STUDENT_USER_BY_ID_RESET = 'DELETE_STUDENT_USER_BY_ID_RESET'
