export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const GET_STUDENT_USERS_REQUEST = 'GET_STUDENT_USERS_REQUEST'
export const GET_STUDENT_USERS_SUCCESS = 'GET_STUDENT_USERS_SUCCESS'
export const GET_STUDENT_USERS_FAIL = 'GET_STUDENT_USERS_FAIL'
export const GET_STUDENT_USERS_RESET = 'GET_STUDENT_USERS_RESET'
